version: "3"

services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=admin
    ports:
      - "1521:1521"
    volumes:
      - ./oracle_data:/opt/oracle/oradata
      - ./scripts:/scripts

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
